### ISSUE TITLE
Check whether or not a batch is complete

### ISSUE THREAD

**Issue by Frakert** [Frakert/Predictive-Maintenance-Membrane-pumpm#1]
Currently the code will just start processing all batches it gets a batchcode from.

However if the data collection starts or stops in such a way only half the batch data is in the dataset this could lead to some weird behavior and even possible false positives or negatives.

To stop this i want to check for this and filter out any and all batches this might apply to.
Possibly also implement a minimum time length of about 20 min to filter out weird batches.

**Comment by FreekKlabbers** [comment]
fixed a few commits back
